#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'tmpdir'

def part_path(tmp_dir, basename, i)
  "#{tmp_dir.join(basename)}_#{i}.ts"
end


url = ARGV[0]
basename = ARGV[1] || url.split('/').last

tmp_dir = Pathname.new(Dir.mktmpdir('download-ts-'))

i = 0
while system("wget -O #{part_path(tmp_dir, basename, i)} #{url}_#{i}.ts")
  i += 1
end

files = (0...i).map { |i| part_path(tmp_dir, basename, i) }

`cat #{files.join(' ')} > #{basename}`
